
################### OAuth 2.0 Configuration ##########################
app-security:
  admin-password: admin
  admin-username: admin@email.com
  default-client-id: myApp
  default-client-secret: secret
  user-password: user
  user-username: user@email.com

custom:
  oauth2:
    kakao:
      client-id: f7747834a929dd0adccbdeb58a108251

################### the keys to enable captcha ###################
google:
  recaptcha:
    key:
      secret: 6LfaHiITAAAAANpDTA_Zflwib95IhDqg2SNRLt4U
      site: 6LfaHiITAAAAAAgZBHl4ZUZAYk5RlOYTr6m2N34X

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

################### Logging Configuration ##########################
logging:
  level:
    net:
      chndol:
        study:
          mybatissample:
            mapper: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

################### Mybatis Configuration ##########################
#mybatis.type-aliases-package=io.sbmcs.domain.dto.security,io.sbmcs.domain.dto.event,io.sbmcs.domain.dto.board
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/mapper/**/*Mapper.xml
  type-aliases-package: io.sbmcs.domain.dto

################### Scheduler Configuration ###################
purge:
  cron:
    expression: 0 0 5 * * ?

server:
  tomcat:
    max-swallow-size: -1

################### JPA Configuration ##########################
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true
        page-parameter: pageNo
        prefix: ''
        qualifier-delimiter: _
        size-parameter: pageSize
      sort:
        sort-parameter: sort
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: ${chunkSize:1000}
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

################### Batch Configuration ###################
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false

  ################### ETC Configuration ##########################
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  main:
    allow-bean-definition-overriding: true
  ################### JavaMail Configuration ##########################
  mail:
    host: smtp.gmail.com
    password: leaven011806230508!!
    port: 465
    properties:
      mail:
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
        transport:
          protocol: smtps
    protocol: smtps
    username: onjsdnjs@gmail.com
  profiles:
      active: dev,asyncMail,affirmative,aop-async-event,method # pointcut,OAuth
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 351931512309187
            client-secret: fd6a20688308ef5d8d3faa105e9f527f
          google:
            client-id: 1099004382515-9ffrh6km19qvtigc0ev2eri272t9b4o6.apps.googleusercontent.com
            client-secret: lRP8m46HDmDsE5tdh993gGZO

################### File ##########################
  servlet:
    multipart:
      file-size-threshold: 10MB
      location: ${java.io.tmpdir}
      max-file-size: 10MB
      max-request-size: 100MB
      resolve-lazily: true

################ Scheduler ##########################
org:
  quartz:
    scheduler:
      instanceName: ApplicationScheduleroverriding
      instanceId: AUTO
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 5
      threadPriority: 5
    plugin:
      shutdownhook:
        class: org.quartz.plugins.management.ShutdownHookPlugin
        cleanShutdown: TRUE
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      tablePrefix: qrtz_
      isClustered: true
      clusterCheckinInterval: 15000
      maxMisfiresToHandleAtATime: 1
      misfireThreshold: 12000
      dataSource: myDataSource
    dataSource:
      myDataSource:
        driver: org.postgresql.Driver
        URL: jdbc:postgresql://localhost:5432/springboot
        user: ENC(MdBblvaXjq7YL23XmHLJgw==)
        password: ENC(r118F0y9cT9+atnsT9SWnV79eL3vxnAS)

file:
  domain: localhost
  summernote-images: file:///D:/study/projects/bootsecurityjpa/src/main/webapp/summernote/images/
  summernote-imagesDir: D:/study/projects/bootsecurityjpa/src/main/webapp/summernote/images
  uploadFilePath: D:/uploadFile/

support:
  email: onjsdnjs@naver.com

################### Spring Security ##########################

application:
  security:
    form:
      login-url: /login
      login-processing-url: /login_proc
      logout-url: /logout
      login-error: /login?error=true
      username-parameter: username
      password-parameter: password
    rest:
      login-processing-url: /api/auth/login
    index-url: /index
    denied-url: /denied
    ignored-matcher-pattern: /static/**,/css/**,/swagger-resources/**,/v2/api-docs,/js/**,/swagger-resources/configuration/ui,/swagger-resources/configuration/security,/images/**,/webjars/**,/**/favicon.ico
    permit-all-pattern: /,/index,/home,/login,/errorpage/**,/swagger-resources/**,/v2/api-docs,/swagger-resources/configuration/ui,/swagger-resources/configuration/security
    remember-me-timeout: 3600
    remember-me-key: anymobi

    oauth2:
      default-success-url: /loginSuccess
      failure-url: /loginFailure

    code:
      image:
        length: 4
        width: 148
        height: 36
        expire-in: 60
        url: /test/img/code
        create-url: /image/code
        login-processing-url: /api/auth/login

      sms:
        length: 4
        expire-in: 120
        url: /mobile/bind,/mobile/unbind,/test/sms/code
        create-url: /sms/code
        login-processing-url: /mobile/login

    session:
      maximum-sessions: 1

################### Spring Cloud - MicroService ##########################

#hystrix:
#  command:
#    productInfo:    # command key. use 'default' for global setting.
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
#      circuitBreaker:
#        requestVolumeThreshold: 1   # Minimum number of request to calculate circuit breaker's health. default 20
#        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50
#    OrderRemoteService#getOrderInfo(String):
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000   # default 1,000ms
#      circuitBreaker:
#        requestVolumeThreshold: 1   # Minimum number of request to calculate circuit breaker's health. default 20
#        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1 # remove immediately service list
    lease-expiration-duration-in-seconds: 2 # remove immediately service list
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address
    registry-fetch-interval-seconds: 3

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS