server:
  port: 8081
################### OAuth 2.0 Configuration ##########################
app-security:
  admin-password: admin
  admin-username: admin@email.com
  default-client-id: myApp
  default-client-secret: secret
  user-password: user
  user-username: user@email.com

custom:
  oauth2:
    kakao:
      client-id: f7747834a929dd0adccbdeb58a108251
spring:
  devtools:
    livereload:
      enabled: true
  profiles:
    active: dev,asyncMail,affirmative,aop-async-event,method # pointcut,OAuth
  datasource:
    password: ENC(MdBblvaXjq7YL23XmHLJgw==)
    url: jdbc:postgresql://localhost:5432/springboot
    username: ENC(r118F0y9cT9+atnsT9SWnV79eL3vxnAS)

################### JavaMail Configuration ##########################
  mail:
    host: smtp.gmail.com
    password: leaven011806230508!!
    port: 465
    properties:
      mail:
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
        transport:
          protocol: smtps
    protocol: smtps
    username: onjsdnjs@gmail.com

################### Security OAuth2 ##########################
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 351931512309187
            client-secret: fd6a20688308ef5d8d3faa105e9f527f
          google:
            client-id: 1099004382515-9ffrh6km19qvtigc0ev2eri272t9b4o6.apps.googleusercontent.com
            client-secret: lRP8m46HDmDsE5tdh993gGZO

################### Spring Security ##########################
application:
  security:
    form:
      login-url: /login
      login-processing-url: /login_proc
      logout-url: /logout
      login-error: /login?error=true
      username-parameter: username
      password-parameter: password
    rest:
      login-processing-url: /api/auth/login
    index-url: /index
    denied-url: /denied
    ignored-matcher-pattern: /static/**,/css/**,/swagger-resources/**,/v2/api-docs,/js/**,/images/**,/webjars/**,/**/favicon.ico
    permit-all-pattern: /,/index,/home,/login,/errorpage/**
    remember-me-timeout: 3600
    remember-me-key: anymobi

    oauth2:
      default-success-url: /loginSuccess
      failure-url: /loginFailure

    code:
      image:
        length: 4
        width: 148
        height: 36
        expire-in: 60
        url: /test/img/code
        create-url: /image/code
        login-processing-url: /api/auth/login

      sms:
        length: 4
        expire-in: 120
        url: /mobile/bind,/mobile/unbind,/test/sms/code
        create-url: /sms/code
        login-processing-url: /mobile/login

    session:
      maximum-sessions: 1

################### Batch Configuration ###################
  batch:
    job:
      names: ${job.name:NONE}
      enabled: false

################ Scheduler ##########################
org:
  quartz:
    scheduler:
      instanceName: ApplicationScheduleroverriding
      instanceId: AUTO
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 5
      threadPriority: 5
    plugin:
      shutdownhook:
        class: org.quartz.plugins.management.ShutdownHookPlugin
        cleanShutdown: TRUE
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      tablePrefix: qrtz_
      isClustered: true
      clusterCheckinInterval: 15000
      maxMisfiresToHandleAtATime: 1
      misfireThreshold: 12000
      dataSource: myDataSource
    dataSource:
      myDataSource:
        driver: org.postgresql.Driver
        URL: jdbc:postgresql://localhost:5432/springboot
        user: ENC(MdBblvaXjq7YL23XmHLJgw==)
        password: ENC(r118F0y9cT9+atnsT9SWnV79eL3vxnAS)

################### Spring Cloud - MicroService ##########################

#hystrix:
#  command:
#    productInfo:    # command key. use 'default' for global setting.
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000
#      circuitBreaker:
#        requestVolumeThreshold: 1   # Minimum number of request to calculate circuit breaker's health. default 20
#        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50
#    OrderRemoteService#getOrderInfo(String):
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 3000   # default 1,000ms
#      circuitBreaker:
#        requestVolumeThreshold: 1   # Minimum number of request to calculate circuit breaker's health. default 20
#        errorThresholdPercentage: 50 # Error percentage to open circuit. default 50

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka,http://127.0.0.1:8763/eureka,http://127.0.0.1:8764/eureka