server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: first
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: first-zone

---
server:
  port: 8002
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: second
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: second-zone

---
server:
  port: 8003
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: third
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8763/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: third-zone

---
server:
  port: 8004
management:
  endpoints:
    web:
      exposure:
        include: "*" 
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: fourth
  boot:
    admin:
      client:
        url: http://localhost:9091/admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8764/eureka/
    prefer-same-zone-eureka: true  
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: fourth-zone