spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false

---
spring:
  profiles:
    active: peer1
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 # remove immediately service list
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false           # Just for demo
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    register-with-eureka: true
    fetch-registry: true

---
spring:
  profiles:
    active: peer2
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 # remove immediately service list
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
