spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false

server:
  peer1Port: 8761
  peer2Port: 8762

---
spring:
  profiles: peer1
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 # remove immediately service list
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false           # Just for demo
  instance:
    hostname: localhost
    metadataMap:
      zone: zone1
    # Either this one or the spring boot name must be the same
    # (it works without setting it too, using the alias UNKNOWN)
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${hostname}:${server.peer2Port}/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: ${server.peer1Port}

---
spring:
  profiles: peer2
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 # remove immediately service list
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false
  instance:
    hostname: localhost
    metadataMap:
      zone: zone2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${hostname}:${server.peer1Port}/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: ${server.peer2Port}