server:
  port: 8761
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: default
  boot:
    admin:
      context-path: /admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 # remove immediately service list
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false           # Just for demo
  instance:
    hostname: 127.0.0.1
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://127.0.0.1:8763/eureka/,http://127.0.0.1:8764/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF      
---
server:
  port: 8762
spring:
  profiles: second
  boot:
    admin:
      context-path: /admin
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 # remove immediately service list
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false           # Just for demo
  instance:
    hostname: 127.0.0.1
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8763/eureka/,http://127.0.0.1:8764/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF  
management:
  endpoints:
    web:
      exposure:
        include: "*"  
---
server:
  port: 8763
spring:
  profiles: third
  boot:
    admin:
      context-path: /admin
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 # remove immediately service list
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false           # Just for demo
  instance:
    hostname: 127.0.0.1
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8764/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
server:
  port: 8764
spring:
  profiles: fourth
  boot:
    admin:
      context-path: /admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 # remove immediately service list
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false           # Just for demo
  instance:
    hostname: 127.0.0.1
    appname: eureka-cluster
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8761/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF 