spring:
  boot:
    admin:
      context-path: /admin
eureka:
  server:
    eviction-interval-timer-in-ms: 3000 # remove immediately service list
    response-cache-update-interval-ms: 1000 # Eureka Server's Response Cache. Default 30,000ms
    enableSelfPreservation: false # Just for demo
  client:
    register-with-eureka: true
    fetch-registry: true

---
server:
  port: 8761
spring:
  profiles: first
eureka:
  instance:
    hostname: eureka-server-first.com
    appname: eureka-cluster
    metadataMap:
      zone: first-zone
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/,http://127.0.0.1:8764/eureka/

---
server:
  port: 8762
spring:
  profiles: second
eureka:
  instance:
    hostname: eureka-server-second.com
    appname: eureka-cluster
    metadataMap:
      zone: second-zone
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8763/eureka/,http://127.0.0.1:8764/eureka/

---
server:
  port: 8763
spring:
  profiles: third
eureka:
  instance:
    hostname: eureka-server-third.com
    appname: eureka-cluster
    metadataMap:
      zone: third-zone
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8764/eureka/

---
server:
  port: 8764
spring:
  profiles: fourth
eureka:
  instance:
    hostname: eureka-server-fourth.com
    appname: eureka-cluster
    metadataMap:
      zone: fourth-zone
  client:
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8761/eureka/