server:
  port: 8001
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: first
eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: first-zone
feign:
  hystrix:
    enabled: true

---
server:
  port: 8002
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: second
eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8762/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: second-zone
feign:
  hystrix:
    enabled: true

---
server:
  port: 8003
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: third
eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8763/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: third-zone
feign:
  hystrix:
    enabled: true

---
server:
  port: 8004
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
    shutdown:
      enabled: true
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: fourth
  boot:
    admin:
      client:
        url: http://localhost:9091/admin
eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:8764/eureka/
    prefer-same-zone-eureka: true  
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    metadataMap:
      zone: fourth-zone
feign:
  hystrix:
    enabled: true