spring:
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    password: leaven011806230508!!
    port: 465
    properties:
      mail:
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
        transport:
          protocol: smtps
    protocol: smtps
    username: onjsdnjs@gmail.com