server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: order-service
  mail:
    host: smtp.gmail.com
    password: leaven011806230508!!
    port: 465
    properties:
      mail:
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
        transport:
          protocol: smtps
    protocol: smtps
    username: onjsdnjs@gmail.com

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1 # remove immediately service list
    lease-expiration-duration-in-seconds: 2 # remove immediately service list
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS