server:
  port: 8001
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: first
eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/,http://127.0.0.1:8764/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    prefer-ip-address: true
    metadataMap:
      zone: first-zone

---
server:
  port: 8002
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: second
eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8761/eureka/,http://127.0.0.1:8763/eureka/,http://127.0.0.1:8764/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    prefer-ip-address: true
    metadataMap:
      zone: second-zone

---
server:
  port: 8003
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: third
eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/,http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8764/eureka/
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    prefer-ip-address: true
    metadataMap:
      zone: third-zone

---
server:
  port: 8004
spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
  profiles: fourth
  boot:
    admin:
      client:
        url: http://127.0.0.1:9091/admin
eureka:
  client:
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://127.0.0.1:8764/eureka/,http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/
    prefer-same-zone-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 8
    lease-renewal-interval-in-seconds: 2
    prefer-ip-address: true
    metadataMap:
      zone: fourth-zone