spring:
  datasource:
    password: ENC(MdBblvaXjq7YL23XmHLJgw==)
    url: jdbc:postgresql://db:5432/springboot
    username: ENC(r118F0y9cT9+atnsT9SWnV79eL3vxnAS)
  rabbitmq:
    host: rabbitmq
    listener:
      prefetch: 10
      retry:
        enabled: true
        max-attempts: 3
    password: guest
    port: 5672
    username: guest
    virtual-host: /springboot
  redis:
    host: redis
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0
