spring:
  datasource:
    password: ENC(MdBblvaXjq7YL23XmHLJgw==)
    url: jdbc:postgresql://localhost:5432/springboot
    username: ENC(r118F0y9cT9+atnsT9SWnV79eL3vxnAS)
  rabbitmq:
    host: 127.0.0.1
    listener:
      prefetch: 10
      retry:
        enabled: true
        max-attempts: 3
    password: guest
    port: 5672
    username: guest
    virtual-host: /springboot
