server:
  port: 8765

zuul:
#  prefix: /api
  routes:
    admin-service:
      sensitive-headers: Set-Cookie,Authorization
      path: /adm/**
      serviceId: admin-service
      strip-prefix: false
    order-service:
      sensitive-headers: Set-Cookie,Authorization
      path: /orders/**
      serviceId: order-service
      strip-prefix: false
    product-service:
      sensitive-headers: Set-Cookie,Authorization
      path: /products/**
      serviceId: product-service
      strip-prefix: false
    event-service:
      sensitive-headers: Set-Cookie,Authorization
      path: /events/**
      serviceId: event-service
      strip-prefix: false
    listener-service:
      sensitive-headers: Set-Cookie,Authorization
      path: /listeners/**
      serviceId: listener-service
      strip-prefix: false
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuul-

eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
#    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    admin-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    order-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    product-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    event-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
    listener-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
  threadpool:
    zuul-admin-service:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
    zuul-order-service:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
    zuul-product-service:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
    zuul-event-service:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true
    zuul-listener-service:
      coreSize: 30
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true

admin-service:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 300000
    ConnectTimeout: 30000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100

order-service:
  ribbon:
    MaxAutoRetriesNextServer: 1 # 다음 서버로 재시도
    ReadTimeout: 300000
    ConnectTimeout: 30000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100

product-service:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 300000
    ConnectTimeout: 30000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100

event-service:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 300000
    ConnectTimeout: 30000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100

listener-service:
  ribbon:
    MaxAutoRetriesNextServer: 1
    ReadTimeout: 300000
    ConnectTimeout: 30000
    MaxTotalConnections: 300
    MaxConnectionsPerHost: 100

management:
  endpoint:
    health:
      show-details: ALWAYS

spring:
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false