server:
  port: 8085

spring:
  zipkin:
    baseUrl: http://zipkin-server/
    enabled : true
  datasource:
    password: ENC(MdBblvaXjq7YL23XmHLJgw==)
    url: jdbc:postgresql://localhost:5432/springboot
    username: ENC(r118F0y9cT9+atnsT9SWnV79eL3vxnAS)

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address