server:
  port: 9999

spring:
  zipkin:
    baseUrl: http://localhost:9411
    enabled : true

eureka:
  instance:
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # default address

turbine:
  aggregator:
#    cluster-config: ORDER-SERVICE
  appConfig: admin-service,order-service,product-service
  clusterNameExpression: "'default'"
# http://localhost:9999/turbine.stream
# http://localhost:9999/turbine.stream?cluster=ORDER-SERVICE