server:
  port: 8001
spring:
  zipkin:
    baseUrl: http://localhost:9411
    enabled : true
  profiles: first
  datasource:
    password: ENC(MdBblvaXjq7YL23XmHLJgw==)
    url: jdbc:postgresql://localhost:5432/springboot
    username: ENC(r118F0y9cT9+atnsT9SWnV79eL3vxnAS)

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

---
server:
  port: 8002
spring:
  profiles: second
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/

---
server:
  port: 8003
spring:
  profiles: third
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/

---
server:
  port: 8004
spring:
  profiles: fourth
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8764/eureka/